default_language_version:
  # default language version for each language
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
            "python-dotenv",
        ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.2"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [ "--load-plugins=pylint_django", "--django-settings-module=diehli_finance.settings" ]
        additional_dependencies: [
            # pylint dependency
            django,
            psycopg2,
            pylint_django,
            "python-dotenv",
            # runtime dependencies
            # ...
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
            # mypy dependencies
            django,
            psycopg2,
            djangorestframework-stubs,
            django-stubs,
            "python-dotenv",
            # runtime dependencies
            # ...
        ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
