# Generated by Django 3.2.18 on 2023-02-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("EKWALI", "Ekwali"),
                            ("Lezin", "Lezin"),
                            ("237Immo", "Immo237"),
                            ("E-wii", "Ewii"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("email", "platform"), name="unique_customer"
            ),
        ),
    ]
