# Generated by Django 3.2.18 on 2023-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="platform",
            field=models.CharField(
                choices=[
                    ("EKWALI", "Ekwali"),
                    ("Lezin", "Lezin"),
                    ("237Immo", "Immo237"),
                    ("E-wii", "Ewii"),
                    ("Afrique Profonde", "Afriqueprofonde"),
                    ("Inside Menoua", "Insidemenoua"),
                    ("Tribal Luxury", "Triballuxury"),
                ],
                max_length=16,
            ),
        ),
    ]
